const tracks={
Happy:[["Raja Ji Ke Dilwa","Pawan Singh","🧡","bhojpuri"],["Kesariya","Arijit Singh","🇮🇳","hindi"],["What Jhumka?","Arijit Singh, Jonita Gandhi","🇮🇳","hindi"],["Gallan Goodiyaan","Yashita Sharma, Farhan Akhtar","🇮🇳","hindi"],["Ilahi","Arijit Singh","🇮🇳","hindi"],["Sunroof","Nicky Youre, dazy","☀️","english"],["Good Life","OneRepublic","🌈","english"],["Levitating","Dua Lipa","✨","english"],["Best Day Of My Life","American Authors","🎉","english"]],
Calm:[["Iktara","Kavita Seth","🌿","hindi"],["Agar Tum Saath Ho","Alka Yagnik, Arijit Singh","💙","hindi"],["Kho Gaye Hum Kahan","Jasleen Royal, Prateek Kuhad","🌙","hindi"],["Kabira (Encore)","Arijit Singh, Harshdeep Kaur","🕊️","hindi"],["Weightless","Marconi Union","🌊","english"],["Bloom","The Paper Kites","🌿","english"],["Sunset Lover","Petit Biscuit","🌅","english"],["Yellow","Coldplay","💛","english"]],
Sad:[["Channa Mereya","Arijit Singh","💔","hindi"],["Tujhe Bhula Diya","Mohit Chauhan, Shekhar Ravjiani","🥀","hindi"],["Hamari Adhuri Kahani","Arijit Singh","🌧️","hindi"],["Mann Bharryaa 2.0","B Praak","💔","hindi"],["Fix You","Coldplay","💙","english"],["Someone Like You","Adele","🌧️","english"],["Lovely","Billie Eilish","🫧","english"],["The Night We Met","Lord Huron","🌌","english"]],
Energetic:[["Zinda","Siddharth Mahadevan","🔥","hindi"],["Kar Har Maidaan Fateh","Shreya Ghoshal, Sukhwinder Singh","🏆","hindi"],["Malhari","Vishal Dadlani","⚔️","hindi"],["Apna Time Aayega","Ranveer Singh","🚀","hindi"],["Believer","Imagine Dragons","🔥","english"],["Blinding Lights","The Weeknd","⚡","english"],["Uptown Funk","Mark Ronson","🕺","english"],["Eye of the Tiger","Survivor","🥊","english"]],
Stressed:[["Kun Faya Kun","A.R. Rahman, Javed Ali, Mohit Chauhan","🕊️","hindi"],["Safarnama","Lucky Ali","🛣️","hindi"],["Alag Aasmaan","Anuv Jain","☁️","hindi"],["Aashiyan","Shreya Ghoshal, Nikhil Paul George","🌿","hindi"],["Lovely Day","Bill Withers","🌤️","english"],["Three Little Birds","Bob Marley","🐦","english"],["Here Comes the Sun","The Beatles","🌱","english"],["Better Together","Jack Johnson","🌴","english"]],
Romantic:[["Tum Se Hi","Mohit Chauhan","❤️","hindi"],["Tum Kya Mile","Arijit Singh, Shreya Ghoshal","💗","hindi"],["Apna Bana Le","Arijit Singh, Sachin-Jigar","🌹","hindi"],["Ranjha","B Praak, Jasleen Royal","💞","hindi"],["Perfect","Ed Sheeran","💍","english"],["Until I Found You","Stephen Sanchez","🌹","english"],["All of Me","John Legend","❤️","english"],["Adore You","Harry Styles","💗","english"]]
};
const keys={Happy:["happy","great","good","excited","awesome","joy","khush"],Calm:["calm","peace","peaceful","relax","quiet","chill","sleep","shaant"],Sad:["sad","lonely","cry","heartbroken","upset","down","hurt","dukhi"],Energetic:["energy","energetic","gym","workout","power","hype","dance"],Stressed:["stress","stressed","pressure","tired","anxious","deadline","overwhelmed","exam","tension"],Romantic:["love","romantic","date","crush","relationship","valentine","pyaar"]};
let stream=null;let currentFilter="all";let currentMood="Calm";const $=id=>document.getElementById(id);
function yt(title,artist){return "https://www.youtube.com/results?search_query="+encodeURIComponent(title+" "+artist+" official song");}
function render(m){
 currentMood=m;
 const list=tracks[m].filter(t=>currentFilter==="all"||t[3]===currentFilter);
 $("tracks").innerHTML=list.map(t=>'<div class="track"><div class="cover">'+t[2]+'</div><div><h4>'+t[0]+'</h4><p>'+t[1]+'</p><span class="lang">'+(t[3]==="hindi"?"Hindi / Bollywood":"English")+'</span></div><button class="play" title="Play on YouTube" onclick="window.open(yt('+JSON.stringify(t[0])+','+JSON.stringify(t[1])+'),\'_blank\')">▶</button></div>').join("");
}
function mood(m,c=92,s="manual"){document.querySelectorAll(".moods button").forEach(b=>b.classList.toggle("active",b.dataset.mood===m));$("detectedMood").textContent=m;$("confidence").textContent=c+"%";$("heroMood").textContent=m;$("heroConfidence").textContent=c+"% confidence · "+s;$("playlistTag").textContent=m+" mood";render(m);$("recommendations").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".moods button").forEach(b=>b.onclick=()=>mood(b.dataset.mood,96,"user input"));
$("textAnalyze").onclick=()=>{let t=$("textInput").value.toLowerCase();if(!t)return alert("Write a short sentence first.");let a=Object.keys(keys).map(m=>[m,keys[m].filter(k=>t.includes(k)).length]).sort((x,y)=>y[1]-x[1])[0];mood(a[1]?a[0]:"Calm",Math.min(97,70+a[1]*8),"text sentiment")};
$("cameraBtn").onclick=async()=>{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;$("video").srcObject=null;document.querySelector(".camera").classList.remove("active");$("cameraBtn").textContent="Enable camera";$("scanBtn").disabled=true;$("cameraPlaceholder").style.display="flex";return}try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$("video").srcObject=stream;document.querySelector(".camera").classList.add("active");$("cameraPlaceholder").style.display="none";$("cameraBtn").textContent="Disable camera";$("scanBtn").disabled=false}catch(e){alert("Camera permission was not granted. You can still use text or manual emotion input.")}};
$("scanBtn").onclick=()=>{document.querySelector(".camera").classList.add("scanning");$("scanBtn").disabled=true;setTimeout(()=>{document.querySelector(".camera").classList.remove("scanning");$("scanBtn").disabled=false;let m=["Calm","Happy","Energetic","Stressed","Romantic","Sad"][Math.floor(Math.random()*6)];mood(m,84,"camera demo")},1600)};
render("Calm");